from config import Config
from datetime import datetime  # ADD THIS IMPORT

class RecommendationSystem:
    
    def __init__(self):
        self.severity_grades = Config.SEVERITY_GRADES
        
        self.recommendations = {
            0: {
                'title': 'Eye appears healthy',
                'advice': [
                    'No signs of hyphema detected',
                    'Continue regular eye check-ups',
                    'Protect eyes from injury during sports/activities',
                    'Wear sunglasses in bright sunlight'
                ],
                'urgency': 'None',
                'action': 'No immediate action required'
            },
            1: {
                'title': 'Mild hyphema detected',
                'advice': [
                    'Monitor symptoms closely',
                    'Rest with head elevated',
                    'Avoid strenuous activities',
                    'Use prescribed eye drops if available',
                    'Follow up with eye doctor within 24-48 hours'
                ],
                'urgency': 'Low',
                'action': 'Schedule appointment with ophthalmologist'
            },
            2: {
                'title': 'Moderate hyphema detected',
                'advice': [
                    'Seek medical attention within 24 hours',
                    'Avoid any physical activity',
                    'Keep head elevated even while sleeping',
                    'Do not rub or press the eye',
                    'Use protective eye shield if available'
                ],
                'urgency': 'Medium',
                'action': 'Consult eye specialist today'
            },
            3: {
                'title': 'Severe hyphema detected',
                'advice': [
                    'Seek immediate medical attention',
                    'Go to emergency room or eye hospital',
                    'Do NOT drive yourself',
                    'Keep eye closed and covered',
                    'Avoid any physical exertion'
                ],
                'urgency': 'High',
                'action': 'Visit emergency room immediately'
            },
            4: {
                'title': 'Critical - Emergency!',
                'advice': [
                    'EMERGENCY - Seek immediate medical help',
                    'Call emergency services or go to ER now',
                    'Keep eye covered and do not move',
                    'Do not eat or drink (may need surgery)',
                    'Avoid any pressure on the eye'
                ],
                'urgency': 'Critical',
                'action': 'CALL EMERGENCY SERVICES NOW'
            }
        }
    
    def get_recommendation(self, severity_grade):
        """Get recommendations based on severity grade"""
        return self.recommendations.get(severity_grade, self.recommendations[0])
    
    def format_recommendation(self, severity_grade, patient_info=None):
        """Format recommendation for display"""
        rec = self.get_recommendation(severity_grade)
        
        formatted = {
            'grade': severity_grade,
            'label': self.severity_grades[severity_grade]['label'],
            'color': self.severity_grades[severity_grade]['color'],
            'title': rec['title'],
            'advice': rec['advice'],
            'urgency': rec['urgency'],
            'action': rec['action'],
            'disclaimer': 'This is an AI-generated recommendation. Please consult a medical professional for accurate diagnosis.'
        }
        return formatted
    
    def generate_report_text(self, severity_grade, prediction, confidence):
        """Generate detailed report text"""
        rec = self.get_recommendation(severity_grade)
        severity_info = self.severity_grades[severity_grade]
        
        report = f"""
        EYE EXAMINATION REPORT
        ======================
        
        Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}
        
        DIAGNOSIS
        ---------
        Finding: {prediction}
        Severity Grade: {severity_grade} - {severity_info['label']}
        Confidence: {confidence*100:.1f}%
        
        {severity_info['description']}
        
        RECOMMENDATIONS
        ---------------
        {rec['title']}
        
        Immediate Actions:
        {rec['action']}
        
        Care Instructions:
        """
        
        for advice in rec['advice']:
            report += f"\n• {advice}"
        
        report += f"""
        
        URGENCY LEVEL: {rec['urgency']}
        
        IMPORTANT DISCLAIMER:
        This report is generated by an AI system for screening purposes only.
        It is not a substitute for professional medical diagnosis.
        Please consult an ophthalmologist for accurate evaluation.
        """
        return report